name: DansPluginManager
version: '${project.version}'
main: dansplugins.dpm.DansPluginManager
api-version: 1.17

commands:
  danspluginmanager:
  dpm:

permissions:
  dpm.help:
    default: true
  dpm.list:
    default: true
  dpm.stats:
    default: true
  dpm.get:
    default: op