name: DansPluginManager
version: '${project.version}'
main: dansplugins.dpm.DansPluginManager
api-version: 1.13

commands:
  danspluginmanager:
  dpm:

permissions:
  dpm.help:
    default: true
