name: ExamplePonderPlugin
version: '${project.version}'
main: preponderous.exampleponderplugin.ExamplePonderPlugin
api-version: 1.13

commands:
  exampleponderplugin:
  epp:

permissions:
  epp.help:
    default: true
